package_assets: on
compress_assets: on
gzip_assets: on
javascript_compressor: yui
embed_assets: off

javascripts:
  snorby:
    - public/javascripts/gmaps4rails/gmaps4rails.base.js
    - public/javascripts/gmaps4rails/gmaps4rails.googlemaps.js
    - public/javascripts/jquery.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/hotkeys.js    
    - public/javascripts/rails.js
    - public/javascripts/handlebars.js
    - public/javascripts/templates.js
    - public/javascripts/easing.js
    - public/javascripts/fancybox.js
    - public/javascripts/growl.js
    - public/javascripts/colorpicker.js
    - public/javascripts/editable.js
    - public/javascripts/scrollto.js
    - public/javascripts/validate.js
    - public/javascripts/tipsy.js
    - public/javascripts/chosen.js
    - public/javascripts/detect_timezone.js
    - public/javascripts/snorby.js
    - public/javascripts/bootstrap.js


stylesheets:
  snorby:
    - public/stylesheets/bootstrap.css
    - public/stylesheets/bootstrap-responsive.css
    - public/stylesheets/grid.css
    - public/stylesheets/snorby.css