# Oids:
#   Required values:
#     info: Descriptive text for oid
#     text: Showed at the top of graph
#     label: Text for tabs
#
#   Optional values:
#     unit: used for graphs
#     reference: oid for reference. The main oid has to be divided for that value
#     mult: if the value shoud be multiplied by a value
#     inverse: boolean value for that (reference - 'main oid')/reference
#
# time: time frecuency to get values
# level_medium: medium value for severtities
# level_high: high value for serverities
# community: value for snmp servers
#


snorby: &snorby
  oids:
    "1.3.6.1.4.1.2021.11.11.0":
      info: "Percentage of CPU time"
      text: "CPU vs Time By Sensor"
      label: "CPU"
      minus: 100
      unit: "%"
#    "1.3.6.1.4.1.2021.11.10.0":
#      info: "Percentages of system CPU time"
#      text: "System CPU vs Time By Sensor"
#      label: "Sys CPU"
#      unit: "%"
    "1.3.6.1.4.1.2021.10.1.3.2":
      info: "Five Minutes Load"
      text: "Load vs Time By Sensor"
      label: "Load"
      unit: ""
    "1.3.6.1.4.1.39483.1.2.2.4.1.2.9.115.104.101.108.108.116.101.115.116.1":
      info: "Percentage RAM used in machine"
      text: "Memory vs Time By Sensor"
      label: "Memory"
      unit: "%"
    "1.3.6.1.4.1.2021.9.1.9.1":
      info: "Percentage of space used on disk"
      text: "Disk vs Time By Sensor"
      label: "HDD"
      unit: "%"

  snort_stats_oid: "1.3.6.1.4.1.39483.1.1.1.4.1.2.9.115.104.101.108.108.116.101.115.116.1"

  time: '5'
  level_medium: '50'
  level_high: '85'
  community: 'cry5t@l'


development:
    <<: *snorby

test:
    <<: *snorby

production:
    <<: *snorby
